language: java
install:
  - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn test jacoco:report
after_success:
  - mvn jacoco:prepare-agent test jacoco:report coveralls:report
jdk:
  - oraclejdk8